### ISSUE TITLE
Introducing `webrunify`

### ISSUE THREAD

**Issue by brechtcs** [RangerMauve/webrun#12]
Not really an issue, but something that might be of interest.

I've created a browserify plugin (and CLI program) called [webrunify](https://github.com/brechtcs/webrunify) to bundle up CommonJS modules written for Node and expose them as ES modules with all their dependencies included. These bundles can then be shared as standalone modules and imported into Webrun or Beaker just like any other ES module:

```js
import lib from 'dat://example.com/lib.bundle.js'
```
I think this could be useful for people who want to use modules from NPM, but prefer to move away from `--allow-require` (as you rightly recommend in the docs).

**Comment by RangerMauve** [comment]
That's awesome!

Would you be interested in doing a PR that links to and describes your tool in the README?

**Comment by brechtcs** [comment]
Yep, will do!

Op ma 3 dec. 2018 16:16 schreef RangerMauve <notifications@github.com:
