### ISSUE TITLE
DatArchive API only persists to memory

### ISSUE THREAD

**Issue by tswast** [RangerMauve/webrun#2]
By default [node-dat-archive](https://github.com/beakerbrowser/node-dat-archive) only writes to memory. It'd be nice if the polyfill wrote to `.webrun/datcache` or this was somehow globally configurable, like how there's a setting when you first run Beaker Browser where to save your dat archives (maybe via an environment variable such as `WEBRUN_DATARCHIVE_DIRECTORY`).

**Comment by tswast** [comment]
Also, it'd be nice to set `latest: true` for my use case in [dat-pin-box](https://github.com/tswast/dat-pin-box) because I want the pinned archives to be easily browsable.

**Comment by RangerMauve** [comment]
I'm actually using [dat-node](https://github.com/beakerbrowser/dat-node) for the Dat interaction and it should already be persisting to `.webrun/datcache` :D

It doesn't write the actual files to those folders, but it writes the content and metadata feeds which can be used for fetching files from the archive. The reason it doesn't copy the "current version" to the FS is that it would result in duplicated content on disk.

**Comment by tswast** [comment]
Cool. I see that now. I think I was confused at first because all my calls to `await archive.download('/')` raise a TimeoutError.

```
{ TimeoutError: Timed out
    at Timeout.setTimeout [as _onTimeout] (/Users/tswast/.nvm/versions/node/v10.10.0/lib/node_modules/@rangermauve/webrun/node_modules/@beaker/dat-node/lib/util.js:21:14)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10) name: 'TimeoutError', timedOut: true }
```

But, if I skip the download step, the next time I run it, I am indeed able to read the `/pins.json` file.

**Comment by tswast** [comment]
Deleting my `.webrun` directory and running again seems to have fixed the timeout errors. I'll close this. Thanks for the help.

**Comment by RangerMauve** [comment]
You know what, I think I saw this happen to me in Beaker! It seems that sometimes, if you already have some content downloaded, invoking `.download()` won't resolve and instead timeout. I tracked it down to [somewhere in hyperdrive](https://github.com/mafintosh/hyperdrive/blob/master/index.js#L330).

The most suspicious part is [here](https://github.com/mafintosh/hyperdrive/blob/master/index.js#L368). I'll open an issue in Beaker to see if it's a bug we're encountering with Dat itself.
