### ISSUE TITLE
Expose globals related to fetch API

### ISSUE THREAD

**Issue by Gozala** [RangerMauve/webrun#23]
There are several web APIs in the context of fetch that I think should be made available:

- [`Headers`](https://developer.mozilla.org/en-US/docs/Web/API/Headers)
- [`Request`](https://developer.mozilla.org/en-US/docs/Web/API/Request)
- [`Response`](https://developer.mozilla.org/en-US/docs/Web/API/Response)

**Comment by RangerMauve** [comment]
Thanks for the PR, released in Version 3.2.0
