### ISSUE TITLE
Missing sessionStorage

### ISSUE THREAD

**Issue by allain** [RangerMauve/webrun#3]
Would work like localStorage but would be bound to the process.id of the shell used to run the script.

**Comment by RangerMauve** [comment]
You mean tha parent of the webrun process?

**Comment by allain** [comment]
Yeah. Opening a new shell would create a new session.

**Comment by allain** [comment]
Fixed. Stores session data in `/tmp/.webrun/session-${process.ppid}`.

**Comment by RangerMauve** [comment]
Would you mind adding some logic to make it work cross platform? (windows)

Ideally temporary folders should use [fs.mkdtemp](https://nodejs.org/api/fs.html#fs_fs_mkdtemp_prefix_options_callback)
